# Winter Contingency Out of Bounds glitches

Before learning how to break out of bounds on the level winter contingency,  You must learn how to spawn and pilot the pedrogas falcon or the Rally point falcon.

# Pedrogas Falcon

    What is it?

This is a falcon that spawns when the falcon that Jun is in is not present.  The Pedrogas falcon is emp-able, enterable, and pilotable when flipped and is commonly used in speedrunning.  The player can manipulate when it spawns and and use this falcon to break out of the map at 4 different locations

    How does it work?

The pedrogas falcon and the rally point falcon both spawn when Jun's falcon is deloaded or trapped in solid space.  The game always wants a falcon present on the map so if Jun's falcon is missing, the game will replace that falcon with a new one.  The special thing about these new falcons is that they can be pilotable by the player, and the reason is is because 

this is the part hybrid explains the nerdy stuff cause idk.  the vehicle is tagged to pilot and generic null Ais and stuff

    How to do it

You need to have Jun's falcon deloaded or stuck in solid space for the pilotable falcon to spawn.  You can accomplish this by hitting loadzones and skipping loadzones if the player is fast enough.  Starting from mission start, once you exit out of the falcon, proceed through the mission until you reach the second building.  This is the building where Noble Team encounters the dead troopers , and the skirmisher runs across the rooftop.  If you jump over the 3rd building and hit the loading done on the other side while Jun's falcon is stuck inside to deloaded bsp, the one that stretches from mission start all the way to the begining of the 2nd building, you can spawn the pedrogas falcon and break out of the map using the first spirit.  If Jun's falcon is not trapped in that bsp you can still spawn the pedrogas falcon; However, you will not have enough time to break out of the map with the first spirit.  You can still break out of the map with this falcon at later points of the mission.  In order to jump over the third building, you can use any of the methods below, note that if you have the acrophobia skull enabled you can simply fly over all the buildings.

1. Barrier Jump
Just before you enter the second building there are 2 tall, slanted rocks stacked ontop of eachother.  You can walk/jump up the first rock column very easily.  Then on the second rock, sprint and jump into the angle of the rocks on the right side and climb as high as you can.  You should be right below the barrier on the high rocks that are part of the mountain, and in the middle of two trees on your right hand side.  Carefully jump to the next closest part of the mountain towards the building, this is very close to the top of the tree closest to the building.  There is also a stretched texture on the rock.  Then carefully jump on the small ledge infront of you.  There should be a tree branch touching that rock.  Lastly, you should be able to sprint jump ontop of the roof of the building.  Another thing you can try to do is jump to a very small ledge to your left, if you miss the jump you might still make it onto the roof.  Note that you will float on a barrier, and it is very slippery so be careful not to slide off.  Follow the curvature of the roof and hug the mountain to your right, or follow the route that the rooftop skirmisher goes, then jump down.  At this point you have successfully skipped the 3rd building. You will not be able to do the barrier jump again with this method because the loadzone that you hit when you jumped down will deload that area.

2. Head jumping
This glitch requires 2 players.  Continue through the mission until you are about to enter the third building, at this point the skirmisher has already ran across the rooftop and you have not entered the next intended building.  To the left of the entrance of the next building, there is a wall with a railing on top of it.  Head jump to the top of that wall and over the railing.  Have the player below die and spawn on the player on the wall.  Perform another head jump onto the roof of the building to your right.  Have the player below spawn on the player on the roof.  Safely jump down and now you have successfully skipped the third building.

3. Spawn bumping
This glitch requires 2 players.  Continue through the mission until you are about to enter the third building, at this point the skirmisher has already ran across the rooftop and you have not entered the next intended building.  To the right and above of the entrance, there is a lower roof.  Jump ontop of that roof by jumping from the left of the destroyed hole.  Have a player on the roof back up to the most left corner (closest to the entrance) and have the player from below die and spawn on the player above.  This player will spawn half in the barrer and half out, the spawning player should immediately be pushed out of the barrier upwards and then float on it.  That player should float to the edge of that roof, have the bottom player spawn on them, then safely jump down.

4. Acrophobia
Simply acro over the buildings.  There will be an area you can fly over on the far left and far right side of the third building.

Once you have succesfully skipped the third building, make your way to the door where you get out of the 3rd building.  Facing the normal mission route, to your right stable there should be a grunt, and around that stable corner there should be another.  Kill either of them for a plasma pistol, if none of them have a plasma pistol then restart mission, or kill a grunt further ahead if you don't want to get out of the map the spirit method.  With your plasma pistol in hand, finally make your way into the 3rd building by progressing backwards into the mission.  You can hit the pedrogas falcon trigger if youjump and hit the ceiling of the roof on the lower level, then run near the stairs so that the falcon can fly above the 3rd building and normally progress through the mission.  EMP that falcon as it flies over the building and pilot the falcon once the pilot flips out from being upside down for too long.

Alternatively you can skip the 3rd building, kill any of the grunts for a plasma pistol, then progress up until right before the second river crossing.  Jun's falcon should progress over the 3rd building and make its way up to you.  Run backwards into the mission, hit the pedrogas falcon load, and the pedrogas falcon should spawn.  This is because Jun's falcon went too far and deloaded off screen and the game allowed you to spawn a new falcon.  EMP that falcon and pilot the falcon once the pilot flips out from being upside down for too long.  If the spirit has already left you can still break out of the map at later points in the mission.

# Rally Point Falcon

For the rally point falcon run through the mission at mission start and speedrun very quickly to the rallypoint where you first enter a spade warthog vehicle.  You should see a falcon spawn above you without Jun.  Alternatively, you can simply load up Rally point Bravo on the Master Chief Collection or Rally point Alpha on the original Halo Reach and the falcon will always spawn above you.  Have a plasma pistol ready and progress until you reach the first area of enemies.  The falcon should be hovering above the mountain to your left.  Emp that falcon and enter the pilot seat.

# Out of the map using the first spirit

This method can be useful for getting out of the map as soon as possible from mission start.  Obtain the pedrogas falcon, but make sure Jun’s falcon is missing and is deloaded inside of the deloaded bsp.  Across the first river a spirit will spawn if you progress far enough.  Fly a little higher than the spirit then fly past it very quickly.  Try to predict it’s movement because you want your falcon to be wedged inside the middle gap of the vehicle as it flies out of bounds.  Be careful of its movement, your falcon is able to interrupt it’s pathing entirely and will skip dropping it’s second wave of grunts in favor of leaving out of bounds.  It will also fly near 2 different trees and tilt upwards at a sharp angle, try to make sure your falcon stays in the middle as much as possible or else it can be pushed out by the trees or fall out by going below it when it makes a sharp upwards angle.  You may need to do this glitch in a very quick manner to accomplish it.

# Out of the map by breaking the waterfall barrier

At any point during the rally point you can get out of the map with the falcon.  You must have the acrophobia skull enabled.  Pilot any of the falcons and take it to the left of the second waterfall.  This is the waterfall that is right after you retrieve a spade vehicle.  There will be a hole in the map where you can go through with lots of fake rocks and fake trees.  When you enter this hole spin your falcon left and right repeatedly until your falcon altitude reaches at least -70.  Then look North-NorthEast and aim your crosshairs at the “M” shaped carve out of the snowy mountain that is outside of the map.  Exit your falcon and if you successfully broke the barrier, you must acro to your North-NorthWest a decent distance to avoid death barriers.  Your falcon should fall through the barrier and land at the bottom of the map.  Safely make your way down after flying and land on the floor if you wish to retrieve your falcon.

# Out of the map using the second spirit

Starting from mission start retrieve the pedrogas falcon, or for a more easier alternative method emp the falcon at the next rallypoint.  This falcon can be stunned if you progress through the mission fast enough to deload Jun’s falcon, OR you can simply start the mission from Rally point Bravo on MCC or Alpha on the original Halo Reach.  Once you emp the falcon make sure it flips upside down so that the pilot will fall out and you will be able to fly it.  Then past the objective by the broken bridge and meet up with the troopers by the river.  Ledge your falcon in between the spirit and stay inside of it until it pushes you out of the barrier.  You can also hit the river objective first and break out if the spirit is at the broken bridge.  Where the troopers are depends on what order you hit the objectives.  When using either area to break out, you may need to fly out of the spirit then back in the spirit because it might fly through rock spires or trees.